# Configurações de conexão com o banco H2 (em memória)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configuração do Console do H2 (para você visualizar o banco no navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configurações de JPA/Hibernate
# O comando 'create-drop' cria as tabelas ao iniciar e as apaga ao fechar o projeto
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true